# Site settings
title: lablog # type your own lablog title here

description: > # this means to ignore newlines until "baseurl:"
  Bachelor's thesis daily lab notes from Juell Sprott. Powered by Jekyll.
  Link to the  public repository can be found here: https://github.com/juellsprott/thesis-novel-objects
baseurl: "/daily-lablog/" # the subpath of your site, e.g. /blog/
url: "https://juellsprott.github.io/" # the base hostname & protocol for your site
include: [ _assets , _projects , _images, _data]

name : Juell Sprott
email :
github_username:
twitter_username:
# website : git@github.com:fdschneider/jekyll-lablog.git

# Build settings
markdown: kramdown
kramdown:
  input: GFM

noindex: true # if true, google will ignore your pages!

defaults:   # overwrite with in YAML frontmatter, e.g. 'place: New York'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      place:  # default Geolocation of posts.
      author: # default author for posts (for multi-authoring)
